#
mule:
  env: local
  
#HTTP Listener Certificate Configuration
tls:
  keystore:
      jksPath: 'mykeystore.jks'
      jksAlias: 'servercert'
      jksKey: '![jZ9aFIvsIbzo/rVxKqDOdQ==]'
      jksPassword: '![jZ9aFIvsIbzo/rVxKqDOdQ==]'

#API Manager config
api:
 autodiscovery:
             id: '18458956'
 flowDirection: 'outbound'
 source: 'SAP'
 action:    
     api-start: 'API START'
     api-end: 'API END'
     process: 'PROCESS'
     call-api: 'CALL API'
     call-extsys: 'CALL EXT-SYS'
 status: 
    initiate: 'INIT'
    success: 'SUCCESS'
    failure: 'FAILURE'
    complete: 'COMPLETE'
 
# HTTP config

http:              
  papvntl1:    
      sapi:
          client_id: 'cb6fea3d3d814a43a7042b301698194d'
          client_secret: '671B051dA51146B8A6eA36490C1B2F05'
          host: 'sgst-papvntl1-sftp-sapi-5ircui.internal-cci3mz.sgp-s1.cloudhub.io'
          port: '8081'         
          basepath: '/api/v1'   
           
  papvntl2:    
      sapi:
          client_id: 'cb6fea3d3d814a43a7042b301698194d'
          client_secret: '671B051dA51146B8A6eA36490C1B2F05'
          host: 'sgst-papvntl2-sftp-sapi-5ircui.internal-cci3mz.sgp-s1.cloudhub.io'
          port: '8081'   
          path: ''      
          basepath: '/api/v1'   
          
  pmpc:    
      sapi:
          client_id: 'cb6fea3d3d814a43a7042b301698194d'
          client_secret: '671B051dA51146B8A6eA36490C1B2F05'
          host: 'sgst-pmpc-sftp-sapi-5ircui.internal-cci3mz.sgp-s1.cloudhub.io'
          port: '8081'   
          path: ''      
          basepath: '/api/v1'   
          
    
  hulft:    
      sapi:
          client_id: 'cb6fea3d3d814a43a7042b301698194d'
          client_secret: '671B051dA51146B8A6eA36490C1B2F05'
          host: 'sgst-hulft-sapi-5ircui.internal-cci3mz.sgp-s1.cloudhub.io'
          port: '8081'   
          path: ''      
          basepath: '/api/v1'   

  pbs:    
      papi:
          client_id: 'cb6fea3d3d814a43a7042b301698194d'
          client_secret: '671B051dA51146B8A6eA36490C1B2F05'
          host: 'sgst-pp-edi-papi-5ircui.internal-cci3mz.sgp-s1.cloudhub.io'
          port: '8081'   
          path: ''      
          basepath: '/api/v1' 
  utilities:    
      papi:
          client_id: 'cb6fea3d3d814a43a7042b301698194d'
          client_secret: '671B051dA51146B8A6eA36490C1B2F05'
          host: 'sgst-audit-papi-5ircui.internal-cci3mz.sgp-s1.cloudhub.io'
          port: '8081'   
          basepath: '/api/v1'
          path:
            backup: '/backup'
            notification: '/notification'
  orders:
    papi:
      client_id: 'cb6fea3d3d814a43a7042b301698194d'
      client_secret: '671B051dA51146B8A6eA36490C1B2F05'
      host: 'sgst-orders-edi-papi-5ircui.internal-cci3mz.sgp-s1.cloudhub.io'
      port: '8081'         
      basepath: '/api/v1'
      poPath: '/purchase-orders'
      prPath: '/purchase-results'  
             
                    


routing:
    systems:
        sftp: ['ECITA']
        hulft: ['SCM_NAVI']
        mm: 
          po: ['EPRO','IPS']
          pr: ['ECITA']
        sd: ['SALES_EDI']
        fi: ['CMS']
      
            
  
backup:              
    system:    
        api:
            host: 'sgst-audit-papi-5ircui.internal-cci3mz.sgp-s1.cloudhub.io'
            port: '8081'   
            path: '/backup'  
            basepath: '/api/v1' 
            client_id: ''
            client_secret: '' 
            input_params:
                direction: "outbound"
                source: "SAP"
notification:              
    system:    
        api:
            host: 'sgst-audit-papi-5ircui.internal-cci3mz.sgp-s1.cloudhub.io'
            port: '8081'   
            path: '/notification'  
            basepath: '/api/v1' 
            client_id: ''
            client_secret: '' 
            input_params:
                direction: "outbound"
                source: "SAP"
                    
 ######################### PCS Subsidiary Paths ######################
pcs:
  PAPVN-TL1:
    rootDirectory: '/PAPVN'
  PAPVN-TL2:
    rootDirectory: '/PAPVNHY'
  PMPC:
    rootDirectory: '/PMPC'          
              
            
                             
secret:
   key: '![GmjenUtO6a1Q5t7umfwmSvcwAX/Hi2XUvySHc/0lJos=]'
   
   
             
#Notification Configuration
amq:
  email:
      publish: 
        url: 'https://mq-us-east-1.anypoint.mulesoft.com/api/v1'
        client:
          id: '3b109a1dd2a84b238e8eaa858e572009'
          secret: 'C569f53f48e44a0aA0c7EcA5115c872f'
        path: 'mq-common-email-utility-sit'
        
        
        
        
json:
  logger:
    application:
      version: '1.0'
      name: 'sgst-mm-edi-eapi'
    env: 'local'
    
    