#%RAML 1.0 Library
usage: Library of Datatypes
types:
  EDIMsgHeader: !include dataTypes/datatype-edi-message-header.raml
  ErrorResponse: !include dataTypes/dataType-edi-error-response.raml
  SuccessResponse: !include dataTypes/dataType-edi-success-response.raml
  SAPEdiFile: !include dataTypes/datatype-sap-edi-file.raml
  SAPNPMEdiFile: !include dataTypes/datatype-sap-npm-edi-file.raml
